build/pupmod-auditd.spec
manifests/to_syslog.pp

(SIMP 106) Refactor auditd module to reflect rsyslog changes

---

.fixtures.yml
.fixtures.yml.local
README.md
spec/classes/to_syslog_spec.rb

SIMP-399 #comment added auditd

(SIMP-399) Add link to JIRA and the wiki in README

---

.fixtures.yml
.puppet-lint.rc
.travis.yml
Gemfile
Rakefile
build/pupmod-auditd.spec
manifests/config.pp
manifests/config/audisp.pp
manifests/config/audit_profiles/simp.pp
manifests/service.pp
metadata.json

SIMP-604 #comment Removed `common` and `functions`
SIMP-604 #comment Updated module meta files
SIMP-604 #comment Fixed failing lint tests

(SIMP-604) Remove common and functions, fix files & tests

---

.travis.yml
CONTRIBUTING.md
metadata.json

This commit synchronizes all common static module assets with current SIMP
module standards.
Also:
- fixed metadata.json
SIMP-667 #comment updated `pupmod-simp-auditd`

(SIMP-667) Normalize common module assets

---

.fixtures.yml
build/pupmod-auditd.spec
manifests/init.pp
metadata.json

Enabling auditd module for compliance checking
SIMP-720 #comment

(SIMP-720) Map 800-53 requirements to hiera

---

CHANGELOG

The changelog order was incorrect
SIMP-2433 #comment Fixed changelog order in auditd

(SIMP-2433) Fixed changelog ordering

---

README.md

Changes according to discussion of readme style with Kendall, Ryan, Tyler, and others.
SIMP-2755 #close

(SIMP-2755) Finished adding reference to readme

---

.gitlab-ci.yml

(SIMP-3185) add gitlabci to simp module

---

CHANGELOG
manifests/config/audit_profiles/simp.pp
manifests/init.pp
metadata.json
spec/classes/config/audit_profiles/simp_spec.rb
templates/rule_profiles/simp/base.erb

* This is *off* by default since it creates a lot of useless noise
SIMP-1729 #close
SIMP-3550 #close
SIMP-3551 #close
SIMP-3552 #close

(SIMP-1729) Added ability to audit 'rpm' and 'yum'

---

.travis.yml
CHANGELOG
metadata.json

Prep for tag and release
SIMP-3685 #comment pupmod-simp-auditd RPM prep

(SIMP-3685) pupmod-simp-auditd - Fix changelog versions

---

.fixtures.yml
.gitlab-ci.yml
CHANGELOG
metadata.json
spec/classes/config/audit_profiles/expected/default_el6_base.rules.txt
spec/classes/config/audit_profiles/expected/default_el7_base.rules.txt
spec/classes/config/audit_profiles/simp_spec.rb
templates/rule_profiles/simp/base.erb

(SIMP-4047) audit: faillock should be tagged login

---

.gitlab-ci.yml
.puppet-lint.rc
.travis.yml
CHANGELOG
Gemfile
manifests/config.pp

(SIMP-4398) Fix bad changelog date

---

.fixtures.yml
.gitlab-ci.yml

(SIMP-4398) Fix .gitlab-ci.yml syntax error

---

.fixtures.yml
.gitlab-ci.yml

SIMP-3903 #comment auditd use concat 4.1.1 in tests

(SIMP-3903) auditd use concat 4.1.1 in tests

---

CHANGELOG

An RPM cannot be built with CHANGELOG dates out of order.
SIMP-4412 #close

(SIMP-4412) Fix bad auditd CHANGELOG entry

---

.gitlab-ci.yml
CHANGELOG
spec/classes/config/audit_profiles/expected/aggressive_el6_base.rules.txt
spec/classes/config/audit_profiles/expected/aggressive_el7_base.rules.txt
spec/classes/config/audit_profiles/expected/basic_el6_base.rules.txt
spec/classes/config/audit_profiles/expected/basic_el7_base.rules.txt
spec/classes/config/audit_profiles/expected/insane_el6_base.rules.txt
spec/classes/config/audit_profiles/expected/insane_el7_base.rules.txt
templates/rule_profiles/simp/base.erb

SIMP-4765 #close
SIMP-4767 #close

(SIMP-4765) Audit create_module and finit_module syscalls

---

.fixtures.yml
CHANGELOG
README.md
manifests/config/audisp/syslog.pp
metadata.json
spec/classes/init_spec.rb

- Better modularization means users can install this stand alone
SIMP-4149 #close

(SIMP-4149) Decoupled module from unnecessary dependencies

---

.gitlab-ci.yml
spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/oel.yml

SIMP-5430 #comment pupmod-simp-auditd

(SIMP-5430) Incorrect env variable and node set key

---

CHANGELOG
Gemfile
metadata.json
spec/acceptance/suites/compliance/21_stig_profile_inspec_spec.rb
spec/acceptance/suites/compliance/22_stig_profile_oscap_spec.rb

* Removed SSG code that was needed by multiple modules
* Added dependency on updated version of simp-beaker-helpers

(SIMP-5540) Update to simp-beaker-helpers 1.13.0

---

CHANGELOG
metadata.json

Formatted Changelog
Pinned Version for Release

(SIMP-MAINT) Fix Version

---

CHANGELOG
manifests/config.pp
metadata.json
spec/classes/config_spec.rb

- Ensure that permissions do not flap on rotated audit log files
Closes #153

Fix permissions flapping

---

CHANGELOG
manifests/config/audisp/syslog.pp
manifests/config/audit_profiles.pp
manifests/config/audit_profiles/built_in.pp
manifests/config/audit_profiles/custom.pp
manifests/config/audit_profiles/simp.pp
manifests/config/audit_profiles/stig.pp
manifests/rule.pp
metadata.json

(#178) Made the mode of the rule files line up with the rule dir

---

CHANGELOG
SIMP/compliance_profiles/checks.yaml
metadata.json
spec/acceptance/suites/compliance/01_simp_profile_inspec_spec.rb
spec/acceptance/suites/compliance/21_stig_profile_inspec_spec.rb

Fix more use of legacy facts
