simp/pupmod-simp-auditd

- build/pupmod-auditd.spec
- manifests/add_rules.pp
- manifests/init.pp
- spec/classes/grub_spec.rb
- spec/classes/init_spec.rb
- spec/classes/to_syslog_spec.rb
- spec/defines/add_rules_spec.rb
Before this commit, lsb* facts in auditd would fail acceptance tests in
other modules (first noticed in rsyslogd).
This commit replaces all instances of the fact $::lsbmajdistrelease with
$::operatingsystemmajrelease.
SIMP-398 #comment Eliminated lsb* facts in auditd
SIMP-435 #close   Eliminated lsb* facts in auditd
> (SIMP-398) Eliminate all uses of lsb* facts

- .puppet-lint.rc
- Gemfile
- README.md
- Rakefile
- manifests/add_rules.pp
- manifests/config.pp
- manifests/params.pp
- manifests/service.pp
Before this commit, auditd would cause several spec tests to fail in
pupmod-simp-common's `secure_mountpoints`.  This commit fixes those
problems, introduces a .puppet-lint.rc, and cleans up minor style
issues.
SIMP-561 #comment Fixed auditd issues that failed spec tests in common.
> (SIMP-561) Fixed failing tests

- CHANGELOG
- manifests/init.pp
- metadata.json
Use `defined()` to test for `undef` state on `$::auditd_version`.  Previously the null case was not checked, causing compilation to fail if strict variable checking was enabled.
> (SIMP-1239) Fix for strict_variables failure

- build/rpm_metadata/requires
Update the requires file for SIMP6 to point to new version of
compliance markup
SIMP-1735  #comment
> (SIMP-1735) Updated version of Compliance Markup for SIMP 6

- CHANGELOG
- manifests/config/audisp/syslog.pp
- spec/classes/config/audisp/syslog_spec.rb
- Changed the default facility to local5.
- Logs will now be picked up by our default security_relevant_logs
string.
- Updated spec test.
SIMP-2007 #close
> (SIMP-2007)Change log facility of audit dispatcher

- spec/acceptance/suites/default/00_base_spec.rb
Set 'simp_options::syslog' to true so that the audit dispatcher
feature is tested and the test passes again.
SIMP-2320 #close
> (SIMP-2320) Fix Auditd Acceptance tests

- CHANGELOG
- manifests/config/audit_profiles/simp.pp
- spec/classes/config/audit_profiles/simp_spec.rb
- templates/rule_profiles/simp/default_drop.erb
- Added a rule to drop audit logs written because of a cron job
- Added corresponding spec test
SIMP-1862 #close
> (SIMP-1862) Add auditd drop rule for crond

- CHANGELOG
- templates/rule_profiles/simp/base.erb
Per the RHEL STIG, the audit base rules have been updated to add:
* Capture of open_by_handle_at
* Watches on /var/log/faillock and /var/log/tallylock
SIMP-2475 #close
SIMP-2476 #close
> (SIMP-2475) Update auditd base rules

- .travis.yml
- CHANGELOG
- manifests/config/audit_profiles/simp.pp
- spec/classes/config/audit_profiles/simp_spec.rb
- spec/spec_helper.rb
- templates/rule_profiles/simp/base.erb
- Split the permissions rules into chmods, chowns, and attrs.
- Disabled chmod auditing by default
SIMP-2550 #close
> (SIMP-2550) Split auditd permissions rules

- manifests/config/audisp/syslog.pp
- manifests/config/audisp_service.pp
- manifests/service.pp
- spec/classes/config/audisp/syslog_spec.rb
The audisp exec was causing runs to not be idempotent if there were no
services set up to listen.
This class should be included by any audisp service that processes logs.
SIMP-2481 #close
> (SIMP-2481) Move the audisp exec into a class

- CHANGELOG
- manifests/init.pp
- metadata.json
- spec/classes/config/audit_profiles/simp_spec.rb
The default failure state for auditd was to panic the system. However,
with the required audit rules for chmod and chown, this was routinely
overflowing the large log buffer that we had put in place.
Instead of arbitrarily increasing the log buffer, we opted to change
the failure state to logging printk messages until we can figure out
how to properly eliminate this failure case.
SIMP-2558 #close
> (SIMP-2558) Changed the default failure to printk

- CHANGELOG
- templates/rule_profiles/simp/base.erb
Some audit rules were incorrectly listed as exit,always. They are now
set to always,exit.
SIMP-2727 #close
> (SIMP-2727) Change rules to always,exit

- CHANGELOG
- manifests/init.pp
- templates/rule_profiles/simp/base.erb
https://simp-project.atlassian.net/browse/SIMP-2939
I believe this line in the base.erb:
`-w /var/log/tallylock -p wa -k <%= @audit_session_files_tag %>`
should be:
`-w /var/log/tallylog -p wa -k <%= @audit_session_files_tag %>`
...and while insmod has both the /usr/sbin and /sbin paths listed, rmmod and modprobe do not, which causes some security scans to fail. For good measure, need to add:
```
-w /usr/sbin/rmmod -p x -k modules
-w /usr/sbin/modprobe -p x -k modules
```
> (SIMP-2939) SIMP audit profile file paths

- CHANGELOG
- Gemfile
- manifests/config.pp
- metadata.json
- spec/acceptance/nodesets/default.yml
- spec/acceptance/suites/default/00_base_spec.rb
- spec/classes/config_spec.rb
- Set service variable needed to ensure rules are generated
upon service start
- Added more checks in acceptance test to verify rules are generated
appropriately
> (SIMP-3202) audit rules not generated CentOS6

- .fixtures.yml
- Gemfile
- spec/acceptance/suites/compliance/00_default_spec.rb
- spec/fixtures/inspec_profiles/RedHat-7-disa_stig/controls/00_Control_Selector.rb
- spec/fixtures/inspec_profiles/RedHat-7-disa_stig/inspec.yml
Updated the tests to match the new patterns and work with the latest
version of inspec
Requires simp-beaker-helpers 1.10.9
SIMP-4679 #comment Update spec tests to working version
> (SIMP-4679) Update compliance tests

- spec/acceptance/suites/compliance/00_default_spec.rb
Switch the compliance tests over to Hiera 5 since Puppet 4.10.4+ broke
the v3 backend in puppet apply.
> (SIMP-4679) Update to Hiera 5 in tests

- CHANGELOG
- Gemfile
- manifests/service.pp
- metadata.json
- spec/classes/init_spec.rb
Setting provider to 'redhat' causes an issue on RHEL7 systems as puppet tries to use sysvinit tools instead of systemd.  Specifically, the error I'm getting on RHEL 7.5 w/Puppet 5.5.2 is:
```
Error: Could not enable auditd: Execution of '/sbin/chkconfig --add auditd' returned 1: error reading information on service auditd: No such file or directory
Error: /Stage[main]/Auditd::Service/Service[auditd]/enable: change from 'false' to 'true' failed: Could not enable auditd: Execution of '/sbin/chkconfig --add auditd' returned 1: error reading information on service auditd: No such file or directory
```
Removing the provider attribute from the service resources fixes the error in RHEL7.  I also tested in RHEL6.
> Use default service provider

- CHANGELOG
- spec/classes/config/audit_profiles/expected/stig_el6_all_custom_tags.txt
- spec/classes/config/audit_profiles/expected/stig_el6_base_rules.txt
- spec/classes/config/audit_profiles/expected/stig_el7_all_custom_tags.txt
- spec/classes/config/audit_profiles/expected/stig_el7_base_rules.txt
- templates/rule_profiles/stig/base.erb
This change adds auditing of restorecon under the SELinux commands
auditing section of the STIG profile.
SIMP-5934 #close #comment add restorecon audit
> (SIMP-5934) Add restorecon audit

- CHANGELOG
- manifests/init.pp
- metadata.json
- spec/classes/config/audit_profiles_spec.rb
- templates/rule_profiles/common/default_drop.epp
Audit processing can be highly optimized if you take the approach that
only specific SELinux types should generally be audited since all other,
non-allowed, actions are audited by SELinux itself.
This patch adds the capability to globally target specific SELinux types
for further audit processing and drop all other material in user space.
SIMP-5959 #close
> (SIMP-5959) Allow users to filter on SELinux types

- CHANGELOG
- manifests/init.pp
- metadata.json
Use Puppet Integer in lieu of simplib's deprecated Puppet 3 to_integer
SIMP-6120 #close
> (SIMP-6120) Convert to_integer() calls

- CHANGELOG
- manifests/config.pp
- metadata.json
- spec/classes/config_spec.rb
The /etc/audit directory is now managed in the same way as the
/etc/audit/rules.d directory. Both will have the same permissions,
ownership, and utilize purge and recourse.
> (SIMP-6104) Manage /etc/audit directory

- CHANGELOG
- manifests/rule.pp
- metadata.json
- spec/defines/rule_spec.rb
Fix a breaking change inadvertantly introduced into auditd::rule
in which the auditd class was no longer included when an auditd::rule
was defined in a manifest.
SIMP-6565 #close
> (SIMP-6565) auditd::rule no longer includes auditd

- CHANGELOG
- manifests/config/audit_profiles/custom.pp
- metadata.json
- spec/classes/config/audit_profiles/custom_spec.rb
Custom profiles had issues where a trailing newline would not be
present when joining on an Array. Now append a trailing newline in all
cases in case of a badly formatted template or Array join.
SIMP-6706 #close
> (SIMP-6706) Fix trailing newline in custom profile

- .fixtures.yml
- .gitlab-ci.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/docker.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/compliance/local.nodesets/default.yml
- Remove EPEL from node sets
- Use correct branch for puppet-systemd in fixtures
- Reinstate compliance tests in GitLab
SIMP-6919 #comment pupmod-simp-auditd
SIMP-6949 #comment pupmod-simp-auditd
SIMP-6962 #close
> (SIMP-6919) Remove unnecessary EPEL repos in node sets

- CHANGELOG
- metadata.json
- spec/classes/config/audit_profiles/expected/simp_el6_aggressive_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el6_all_rules_custom_tags.txt
- spec/classes/config/audit_profiles/expected/simp_el6_basic_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el6_insane_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el7_aggressive_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el7_all_rules_custom_tags.txt
- spec/classes/config/audit_profiles/expected/simp_el7_basic_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el7_insane_rules.txt
- templates/rule_profiles/simp/base.epp
Fixes: [SIMP-7005](https://simp-project.atlassian.net/browse/SIMP-7005)
A recent Nessus scan recommends monitoring `/usr/share/selinux/` as well as `/etc/selinux/`.
Reference Information:
- 800-171|3.3.1
- 800-171|3.3.2
- 800-53|AU-12
- CCE|CCE-27168-4
- CN-L3|7.1.3.3(a)
- CN-L3|7.1.3.3(b)
- CN-L3|7.1.3.3(c)
- CSF|DE.CM-1
- CSF|DE.CM-3
- CSF|DE.CM-7
- CSF|PR.PT-1
- HIPAA|164.312(b)
- ISO/IEC-27001|A.12.4.1
- ITSG-33|AU-12
- LEVEL|2S
- NESA|T3.6.2
- NESA|T3.6.5
- NESA|T3.6.6
- NIAv2|SM8
- PCI-DSS|10.1
- PCI-DSS|10.2
- SWIFT-CSCv1|6.4
- TBA-FIISB|45.1.1"
See Also: https://workbench.cisecurity.org/files/1858
> (SIMP-7005) Monitor changes to /usr/share/selinux/

- manifests/config/audit_profiles/custom.pp
Fixes: [SIMP-7007](https://simp-project.atlassian.net/browse/SIMP-7007)
The `@example` at the top of the [`auditd::config::audit_profiles::custom`](https://github.com/simp/pupmod-simp-auditd/blob/master/manifests/config/audit_profiles/custom.pp#L5-L25) class needs updating.
> (SIMP-7007) Fix custom profile example docs.

- CHANGELOG
- data/common.yaml
- spec/classes/config/audisp/syslog_spec.rb
- set defaults for auditd syslog plugin  parameters in hiera to ensure if
the auditd version is not defined, that they are set.
> (SIMP-7116) Auditd Defaults

- .gitlab-ci.yml
EL8 doesn't have a 5.5.10 release available so the minimum version
should be bumped to 5.5.16 to align with 2018.1.9(LTS)
> (SIMP-MAINT) Bump puppet agent version to 5.5.16

- metadata.json
Needed by `auditd::config::grub` even if `grub_enable == false`.
`augeasproviders_grub` provides the `kernel_parameter` type.
> Add missing augeasproviders_grub dependency

- CHANGELOG
- manifests/rule.pp
- metadata.json
The substituation was only for the first bad-character.
This fix will change that to substitute all bad-characters in the $title of the ressource.
> fixing regsubs for substituting bad characters

- CHANGELOG
- Gemfile
- manifests/config.pp
- spec/acceptance/suites/compliance/01_simp_profile_inspec_spec.rb
- spec/acceptance/suites/compliance/21_stig_profile_inspec_spec.rb
- spec/acceptance/suites/compliance/22_stig_profile_oscap_spec.rb
- spec/acceptance/suites/compliance/local.nodesets/default.yml
- spec/acceptance/suites/default/00_base_spec.rb
- spec/acceptance/suites/default/10_alt_audit_profiles_spec.rb
- spec/acceptance/suites/default/99_disable_audit_kernel_spec.rb
- spec/classes/config/audit_profiles/expected/stig_el7_all_custom_tags.txt
- spec/classes/config/audit_profiles/expected/stig_el7_base_rules.txt
- spec/classes/config_spec.rb
- templates/rule_profiles/stig/base.epp
- Added a File statement for /etc/audit/audit.rules.prev to prevent unnecessary
flapping
- Ensure that the inspec tests don't run if there isn't a profile available
- Ensure that kmod is audited in all STIG modes on EL7+
[SIMP-7829] #close
[SIMP-7829]: https://simp-project.atlassian.net/browse/SIMP-7829
> (SIMP-7829) - Compliance Updates

- .gitlab-ci.yml
- .travis.yml
- Gemfile
This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7902 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-auditd
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-auditd
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855
> (SIMP-7848) Add PE2019.8 to pupmod-simp-auditd GL pipeline

- .gitlab-ci.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/nodesets/rhel8.yml
- spec/acceptance/suites/compliance/local.nodesets/default.yml
This patch moves the recent `BEAKER_VAGRANT_MEMSIZE` variable out of the 
puppet(sync)-managed section of `.gitlab-ci.yml` and into the compliance 
jobs' `script` sections.
This fixes an issue where the new `variables` section overwrote all YAML
anchor-provided variables, restores the global canary variable 
`PUPPET_VERSION: UNDEFINED`, and persist the nodeset variable
`BEAKER_VAGRANT_MEMSIZE` between puppetsyncs.
SIMP-8123 #close
> (SIMP-8123) Fix variables for GLCI acceptance tests

- CHANGELOG
- manifests/config.pp
- manifests/config/audisp_service.pp
- manifests/init.pp
- manifests/service.pp
- metadata.json
- spec/acceptance/suites/default/90_disable_audit_spec.rb
- spec/classes/init_spec.rb
- Ensure that the auditd service is not managed if the kernel is not enforcing
auditing
- Add an acceptance test for toggling disabling auditing without modifying the
kernel parameter
SIMP-6839 #comment Ensure that the audit service can be correctly managed based on the kernel state
> (SIMP-6839) Audit service and kernel config align

- CHANGELOG
- REFERENCE.md
- functions/calculate_space_left.pp
- functions/validate_init_params.pp
- manifests/init.pp
- metadata.json
- spec/classes/config_spec.rb
- spec/classes/init_spec.rb
- Allow auditd space_left and admin_space_left to accept percentages on
supported versions.
SIMP-8341 #close
> (SIMP-8341) Accept percentages for *space_left

- .gitlab-ci.yml
- CHANGELOG
- Gemfile
- manifests/config/logging.pp
- metadata.json
- spec/classes/config_spec.rb
- Fixed a bug in which the module could not enable auditing in a system
with auditing already disabled in the kernel, when replication of the
audit logs to syslog was required.
- Manifest would fail to compile because of a nil `auditd_version` fact.
SIMP-8791 close
> (SIMP-8791) auditd cannot be enabled in specific case

- .github/workflows/pr_glci.yml
- .github/workflows/pr_glci_manual.yml
- .github/workflows/pr_tests.yml
- .gitlab-ci.yml
This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9288] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-auditd
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-auditd
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …
> (SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-auditd

- CHANGELOG
- spec/acceptance/suites/default/00_base_spec.rb
- spec/classes/config/audit_profiles/built_in_spec.rb
- spec/classes/config/audit_profiles/expected/simp_el6_aggressive_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el6_all_rules_custom_tags.txt
- spec/classes/config/audit_profiles/expected/simp_el6_basic_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el6_insane_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el7_aggressive_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el7_all_rules_custom_tags.txt
- spec/classes/config/audit_profiles/expected/simp_el7_basic_rules.txt
- spec/classes/config/audit_profiles/expected/simp_el7_insane_rules.txt
- spec/classes/config/audit_profiles/expected/stig_el6_all_custom_tags.txt
- spec/classes/config/audit_profiles/expected/stig_el6_base_rules.txt
- spec/classes/config/audit_profiles/expected/stig_el7_all_custom_tags.txt
- spec/classes/config/audit_profiles/expected/stig_el7_base_rules.txt
- spec/classes/config/audit_profiles/simp_spec.rb
- spec/classes/config/audit_profiles/stig_spec.rb
- spec/defines/rule_spec.rb
- templates/rule_profiles/simp/base.epp
- templates/rule_profiles/stig/base.epp
Fixed:
- Switch auditd rules to be 'always,exit' instead of 'exit,always' to match the
man pages and general scanner updates.
SIMP-9602 #close
> (SIMP-9602) Switch to 'always,exit'

- spec/acceptance/suites/compliance/nodesets/centos8.yml
- spec/spec_helper_acceptance.rb
- Restored compliance suite's centos8 nodeset which is used in .gitlab-ci.yml
- Fail acceptance tests if no examples are run.
SIMP-9666 #comment pupmod-simp-auditd acceptance tests configured
> (SIMP-MAINT) Restore compliance suite's centos8 nodeset

- .fixtures.yml
- Unpin systemd in fixtures to ensure testing with latest
- Make sure all fixture URLs end in '.git', as not all private
GitHub mirrors allow shortened URL
> (SIMP-MAINT) auditd: Unpin systemd in fixtures

- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/compliance/nodesets/centos8.yml
- update the EL8 nodes in the acceptance tests
to run with generic/centos8 to make sure they using
CentOS 8.4
- update oel nodeset to use generic box instead of
onyxpoint box
SIMP-10204 #comment auditd updates
SIMP-10209 #close
> (SIMP-10204) Ensure testing with CentOS 8.4

- CHANGELOG
- manifests/config.pp
- metadata.json
- spec/classes/config_spec.rb
Sets the directory permissions to ensure $log_group can traverse the parent directory.
Also sets permissions on /etc/audit/audit.rules.
> (SIMP-MAINT) Set permissions on /var/log/audit.

- CHANGELOG
- manifests/config.pp
- metadata.json
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/nodesets/rhel8.yml
- spec/acceptance/suites/compliance/nodesets/centos8.yml
- spec/acceptance/suites/compliance/nodesets/default.yml
- spec/acceptance/suites/default/00_base_spec.rb
- spec/classes/config_spec.rb
The previous fix did not address the case of the rotated files changing
to mode 400 properly
Closes #155
> Properly fix flapping rotated audit files

- CHANGELOG
- REFERENCE.md
- manifests/init.pp
- metadata.json
- templates/rule_profiles/common/head.epp
This patch makes parameter `$auditd::backlog_wait_time` optional by adding 
a new parameter, `$auditd::backlog_wait_time_enable`.
See [SIMP-10737](https://simp-project.atlassian.net/browse/SIMP-10737) for more details.
SIMP-10737 #close
> (SIMP-10737) make parameter $auditd::backlog_wait_time optional

- CHANGELOG
- manifests/init.pp
- metadata.json
- spec/classes/config/audit_profiles/simp_spec.rb
- spec/classes/init_spec.rb
- templates/rule_profiles/simp/base.epp
I have a number of raspberry pi 4's that are running EL7 which do not use grub.
```bash
CentOS Linux release 7.9.2009 (AltArch)
```
This PR fixes an epp template error and this error from attempting to modify the kernel cmdline via grub.
```
Notice: /Stage[main]/Auditd::Config::Grub/Reboot_notify[audit]: Dependency Kernel_parameter[audit] has failures: true
Warning: /Stage[main]/Auditd::Config::Grub/Reboot_notify[audit]: Skipping because of failed dependencies
Error: Could not find a suitable provider for kernel_parameter
Error: post_resource_eval failed for provider Puppet::Type::Reboot_notify::ProviderNotify
```
> add support for systems thats do not use grub

- .github/workflows/pr_tests.yml
- .gitlab-ci.yml
- Gemfile
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/compliance/nodesets/centos9.yml
This patch moves puppet 6 refs to 7, puppet 7 refs to 8. Then we manually
update all spec nodesets to point to sicura oel boxes and comment out all 
pup8 tests.
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
> Removes puppet 6 from .gitlab-ci.yml

- spec/classes/config/audit_profiles/custom_spec.rb
This should fix the `Unknown variable: 'auditd::config::config_file_mode'` errors during the `auditd::config::audit_profiles::custom` test
> Fix spec test mock

- CHANGELOG
- REFERENCE.md
- manifests/config.pp
- manifests/init.pp
- metadata.json
- spec/classes/config_spec.rb
Module currently purges unmanaged files from /etc/audit/rules.d
This cannot be customised. Adding boolean to specify behaviour as required.
Default remains unchanged.
Fixes #186 
https://simp-project.atlassian.net/browse/SIMP-10744
Unit tests + beaker passing. Additional unit test added for new parameter.
> Add option to not purge unmanages files under /etc/audit/rules.d/ - SIMP-10744

- CHANGELOG
- SIMP/compliance_profiles/checks.yaml
- metadata.json
- spec/classes/config/audit_profiles/simp_spec.rb
- spec/classes/config_spec.rb
On Puppet 8, [strict](https://www.puppet.com/docs/puppet/8/configuration.html#strict) is set to `error` by default.  This causes [`deprecation()`](https://forge.puppet.com/modules/puppetlabs/stdlib/reference#deprecation) to fail and output an error message.
This change avoids the calls to deprecated parameters where possible and checks the value of `strict` in tests where the deprecated parameters are used intentionally.
> Remove calls to deprecated parameters

- CHANGELOG
- functions/validate_init_params.pp
- metadata.json
- spec/classes/init_spec.rb
> Fix space_left/admin_space_left as percentages
